components:
  schemas:
    Any:
      additionalProperties: {}
      properties:
        '@type':
          type: string
      type: object
    CreateKnowledgeBaseResponse:
      properties:
        knowledge_base:
          $ref: '#/components/schemas/KnowledgeBase'
      type: object
    DeleteKnowledgeBaseResponse:
      type: object
    GetKnowledgeBaseResponse:
      properties:
        knowledge_base:
          $ref: '#/components/schemas/KnowledgeBase'
      type: object
    KnowledgeBase:
      properties:
        description:
          type: string
        display_name:
          type: string
        embedding_generator:
          $ref: '#/components/schemas/KnowledgeBase.EmbeddingGenerator'
        generation:
          $ref: '#/components/schemas/KnowledgeBase.Generation'
        id:
          readOnly: true
          type: string
        indexer:
          $ref: '#/components/schemas/KnowledgeBase.Indexer'
        retrieval_api_url:
          readOnly: true
          type: string
        retriever:
          $ref: '#/components/schemas/KnowledgeBase.Retriever'
        tags:
          additionalProperties:
            type: string
          description: Optional list of tags to attach to a pipeline.
          type: object
        vector_database:
          $ref: '#/components/schemas/KnowledgeBase.VectorDatabase'
      required:
        - id
        - display_name
        - vector_database
        - embedding_generator
        - generation
      type: object
    KnowledgeBase.EmbeddingGenerator:
      properties:
        dimensions:
          format: int32
          type: integer
        model:
          type: string
        provider:
          $ref: '#/components/schemas/KnowledgeBase.EmbeddingGenerator.Provider'
      required:
        - provider
        - dimensions
        - model
      type: object
    KnowledgeBase.EmbeddingGenerator.Provider:
      properties:
        cohere:
          $ref: '#/components/schemas/KnowledgeBase.EmbeddingGenerator.Provider.Cohere'
        openai:
          $ref: '#/components/schemas/KnowledgeBase.EmbeddingGenerator.Provider.OpenAI'
      type: object
    KnowledgeBase.EmbeddingGenerator.Provider.Cohere:
      properties:
        api_key:
          type: string
        base_url:
          type: string
      required:
        - api_key
      type: object
    KnowledgeBase.EmbeddingGenerator.Provider.OpenAI:
      properties:
        api_key:
          type: string
      type: object
    KnowledgeBase.Generation:
      properties:
        model:
          type: string
        provider:
          $ref: '#/components/schemas/KnowledgeBase.Generation.Provider'
      required:
        - provider
        - model
      type: object
    KnowledgeBase.Generation.Provider:
      properties:
        openai:
          $ref: '#/components/schemas/KnowledgeBase.Generation.Provider.OpenAI'
      type: object
    KnowledgeBase.Generation.Provider.OpenAI:
      properties:
        api_key:
          type: string
      type: object
    KnowledgeBase.Indexer:
      properties:
        chunk_overlap:
          format: int32
          type: integer
        chunk_size:
          format: int32
          type: integer
        input_topics:
          items:
            type: string
          type: array
        redpanda_password:
          type: string
        redpanda_sasl_mechanism:
          $ref: '#/components/schemas/SASLMechanism'
        redpanda_username:
          type: string
      required:
        - input_topics
      type: object
    KnowledgeBase.Retriever:
      properties:
        reranker:
          $ref: '#/components/schemas/KnowledgeBase.Retriever.Reranker'
      type: object
    KnowledgeBase.Retriever.Reranker:
      properties:
        enabled:
          type: boolean
        provider:
          $ref: '#/components/schemas/KnowledgeBase.Retriever.Reranker.Provider'
      type: object
    KnowledgeBase.Retriever.Reranker.Provider:
      properties:
        cohere:
          $ref: '#/components/schemas/KnowledgeBase.Retriever.Reranker.Provider.Cohere'
      type: object
    KnowledgeBase.Retriever.Reranker.Provider.Cohere:
      properties:
        api_key:
          type: string
        model:
          type: string
      required:
        - api_key
        - model
      type: object
    KnowledgeBase.VectorDatabase:
      properties:
        postgres:
          $ref: '#/components/schemas/KnowledgeBase.VectorDatabase.Postgres'
      type: object
    KnowledgeBase.VectorDatabase.Postgres:
      properties:
        dsn:
          type: string
        table:
          type: string
      required:
        - dsn
        - table
      type: object
    KnowledgeBaseCreate:
      properties:
        description:
          type: string
        display_name:
          type: string
        embedding_generator:
          $ref: '#/components/schemas/KnowledgeBaseCreate.EmbeddingGenerator'
        generation:
          $ref: '#/components/schemas/KnowledgeBaseCreate.Generation'
        indexer:
          $ref: '#/components/schemas/KnowledgeBaseCreate.Indexer'
        retriever:
          $ref: '#/components/schemas/KnowledgeBaseCreate.Retriever'
        tags:
          additionalProperties:
            type: string
          description: Optional list of tags to attach to a pipeline.
          type: object
        vector_database:
          $ref: '#/components/schemas/KnowledgeBaseCreate.VectorDatabase'
      required:
        - display_name
        - vector_database
        - embedding_generator
      type: object
    KnowledgeBaseCreate.EmbeddingGenerator:
      properties:
        dimensions:
          format: int32
          type: integer
        model:
          type: string
        provider:
          $ref: '#/components/schemas/KnowledgeBaseCreate.EmbeddingGenerator.Provider'
      required:
        - provider
        - dimensions
        - model
      type: object
    KnowledgeBaseCreate.EmbeddingGenerator.Provider:
      properties:
        cohere:
          $ref: '#/components/schemas/KnowledgeBaseCreate.EmbeddingGenerator.Provider.Cohere'
        openai:
          $ref: '#/components/schemas/KnowledgeBaseCreate.EmbeddingGenerator.Provider.OpenAI'
      type: object
    KnowledgeBaseCreate.EmbeddingGenerator.Provider.Cohere:
      properties:
        api_key:
          type: string
        base_url:
          type: string
      required:
        - api_key
      type: object
    KnowledgeBaseCreate.EmbeddingGenerator.Provider.OpenAI:
      properties:
        api_key:
          type: string
      type: object
    KnowledgeBaseCreate.Generation:
      properties:
        model:
          type: string
        provider:
          $ref: '#/components/schemas/KnowledgeBaseCreate.Generation.Provider'
      required:
        - provider
        - model
      type: object
    KnowledgeBaseCreate.Generation.Provider:
      properties:
        openai:
          $ref: '#/components/schemas/KnowledgeBaseCreate.Generation.Provider.OpenAI'
      type: object
    KnowledgeBaseCreate.Generation.Provider.OpenAI:
      properties:
        api_key:
          type: string
      type: object
    KnowledgeBaseCreate.Indexer:
      properties:
        chunk_overlap:
          format: int32
          type: integer
        chunk_size:
          format: int32
          type: integer
        input_topics:
          items:
            type: string
          type: array
        redpanda_password:
          type: string
        redpanda_sasl_mechanism:
          $ref: '#/components/schemas/SASLMechanism'
        redpanda_username:
          type: string
      required:
        - input_topics
      type: object
    KnowledgeBaseCreate.Retriever:
      properties:
        reranker:
          $ref: '#/components/schemas/KnowledgeBaseCreate.Retriever.Reranker'
      type: object
    KnowledgeBaseCreate.Retriever.Reranker:
      properties:
        enabled:
          type: boolean
        provider:
          $ref: '#/components/schemas/KnowledgeBaseCreate.Retriever.Reranker.Provider'
      type: object
    KnowledgeBaseCreate.Retriever.Reranker.Provider:
      properties:
        cohere:
          $ref: '#/components/schemas/KnowledgeBaseCreate.Retriever.Reranker.Provider.Cohere'
      type: object
    KnowledgeBaseCreate.Retriever.Reranker.Provider.Cohere:
      properties:
        api_key:
          type: string
        model:
          type: string
      required:
        - api_key
        - model
      type: object
    KnowledgeBaseCreate.VectorDatabase:
      properties:
        postgres:
          $ref: '#/components/schemas/KnowledgeBaseCreate.VectorDatabase.Postgres'
      type: object
    KnowledgeBaseCreate.VectorDatabase.Postgres:
      properties:
        dsn:
          type: string
        table:
          type: string
      required:
        - dsn
        - table
      type: object
    KnowledgeBaseUpdate:
      properties:
        description:
          type: string
        display_name:
          type: string
        embedding_generator:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.EmbeddingGenerator'
        generation:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.Generation'
        indexer:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.Indexer'
        retriever:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.Retriever'
        tags:
          additionalProperties:
            type: string
          description: Optional list of tags to attach to a pipeline.
          type: object
        vector_database:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.VectorDatabase'
      required:
        - display_name
        - vector_database
        - embedding_generator
      type: object
    KnowledgeBaseUpdate.EmbeddingGenerator:
      properties:
        provider:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.EmbeddingGenerator.Provider'
      required:
        - provider
      type: object
    KnowledgeBaseUpdate.EmbeddingGenerator.Provider:
      properties:
        cohere:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.EmbeddingGenerator.Provider.Cohere'
        openai:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.EmbeddingGenerator.Provider.OpenAI'
      type: object
    KnowledgeBaseUpdate.EmbeddingGenerator.Provider.Cohere:
      properties:
        api_key:
          type: string
        base_url:
          type: string
      type: object
    KnowledgeBaseUpdate.EmbeddingGenerator.Provider.OpenAI:
      properties:
        api_key:
          type: string
      type: object
    KnowledgeBaseUpdate.Generation:
      properties:
        provider:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.Generation.Provider'
      required:
        - provider
      type: object
    KnowledgeBaseUpdate.Generation.Provider:
      properties:
        openai:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.Generation.Provider.OpenAI'
      type: object
    KnowledgeBaseUpdate.Generation.Provider.OpenAI:
      properties:
        api_key:
          type: string
      type: object
    KnowledgeBaseUpdate.Indexer:
      properties:
        chunk_overlap:
          format: int32
          type: integer
        chunk_size:
          format: int32
          type: integer
        input_topics:
          items:
            type: string
          type: array
        redpanda_password:
          type: string
        redpanda_sasl_mechanism:
          $ref: '#/components/schemas/SASLMechanism'
        redpanda_username:
          type: string
      required:
        - input_topics
      type: object
    KnowledgeBaseUpdate.Retriever:
      properties:
        reranker:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.Retriever.Reranker'
      type: object
    KnowledgeBaseUpdate.Retriever.Reranker:
      properties:
        enabled:
          type: boolean
        provider:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.Retriever.Reranker.Provider'
      type: object
    KnowledgeBaseUpdate.Retriever.Reranker.Provider:
      properties:
        cohere:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.Retriever.Reranker.Provider.Cohere'
      type: object
    KnowledgeBaseUpdate.Retriever.Reranker.Provider.Cohere:
      properties:
        api_key:
          type: string
        model:
          type: string
      required:
        - api_key
        - model
      type: object
    KnowledgeBaseUpdate.VectorDatabase:
      properties:
        postgres:
          $ref: '#/components/schemas/KnowledgeBaseUpdate.VectorDatabase.Postgres'
      type: object
    KnowledgeBaseUpdate.VectorDatabase.Postgres:
      properties:
        dsn:
          type: string
      required:
        - dsn
      type: object
    ListKnowledgeBasesRequest.Filter:
      properties:
        name_contains:
          description: Any KnowledgeBase that partially match this name will be returned.
          type: string
        tags[string]:
          additionalProperties:
            type: string
          description: KnowledgeBases that match all the provided tags will be returned.
          type: object
      type: object
    ListKnowledgeBasesResponse:
      properties:
        knowledge_bases:
          items:
            $ref: '#/components/schemas/KnowledgeBase'
          type: array
        next_page_token:
          type: string
      type: object
    SASLMechanism:
      description: SASL mechanism to use for authentication.
      enum:
        - SASL_MECHANISM_SCRAM_SHA_256
        - SASL_MECHANISM_SCRAM_SHA_512
      type: string
    Status:
      properties:
        code:
          format: int32
          type: integer
        details:
          items:
            $ref: '#/components/schemas/Any'
          type: array
        message:
          type: string
      type: object
    UpdateKnowledgeBaseResponse:
      properties:
        knowledge_base:
          $ref: '#/components/schemas/KnowledgeBase'
      type: object
  securitySchemes:
    auth0:
      description: RedpandaCloud
      flows:
        implicit:
          authorizationUrl: https://auth.prd.cloud.redpanda.com/oauth/authorize
          scopes: {}
          x-client-id: dQjapNIAHhF7EQqQToRla3yEII9sUSap
      type: oauth2
info:
  title: Redpanda Cloud Data Plane API
  version: v1
openapi: 3.0.3
paths:
  /v1alpha3/knowledge-bases:
    get:
      operationId: KnowledgeBaseService_ListKnowledgeBases
      parameters:
        - description: Limit the paginated response to a number of items. Defaults to 100. Use -1 to disable pagination.
          in: query
          name: page_size
          schema:
            format: int32
            type: integer
        - in: query
          name: page_token
          schema:
            type: string
        - description: Any KnowledgeBase that partially match this name will be returned.
          in: query
          name: filter.name_contains
          schema:
            type: string
        - description: This is a request variable of the map type. The query format is "map_name[key]=value", e.g. If the map name is Age, the key type is string, and the value type is integer, the query parameter is expressed as Age["bob"]=18
          in: query
          name: filter.tags[string]
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      tags:
        - KnowledgeBaseService
    post:
      operationId: KnowledgeBaseService_CreateKnowledgeBase
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KnowledgeBaseCreate'
        required: true
        x-originalParamName: knowledge_base
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      tags:
        - KnowledgeBaseService
  /v1alpha3/knowledge-bases/{id}:
    delete:
      operationId: KnowledgeBaseService_DeleteKnowledgeBase
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      tags:
        - KnowledgeBaseService
    get:
      operationId: KnowledgeBaseService_GetKnowledgeBase
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      tags:
        - KnowledgeBaseService
    put:
      operationId: KnowledgeBaseService_UpdateKnowledgeBase
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: update_mask
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KnowledgeBaseUpdate'
        required: true
        x-originalParamName: knowledge_base
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      tags:
        - KnowledgeBaseService
security:
  - auth0: []
servers:
  - description: Data Plane API
    url: '{dataplane_api_url}'
    variables:
      dataplane_api_url:
        default: https://{dataplane_api_url}
        description: |-
          Find the Data Plane API base URL of a cluster by calling the Get Cluster endpoint of the Control Plane API. The dataplane_api.url field is returned in the response body.<br><br>
          					Example (Dedicated): "https://api-a4cb21.ck09mi9c4vs17hng9gig.fmc.prd.cloud.redpanda.com"<br>
          					Example (BYOC): "https://api-a4cb21.ck09mi9c4vs17hng9gig.byoc.prd.cloud.redpanda.com"
tags:
  - description: Create and manage retrieval-augmented generation (RAG) knowledge bases.
    name: Redpanda AI KnowledgeBase
