// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBrokerConfig(arg1) {
  return window['go']['main']['App']['GetBrokerConfig'](arg1);
}

export function GetBrokersWithLogDirs() {
  return window['go']['main']['App']['GetBrokersWithLogDirs']();
}

export function GetClusterInfo() {
  return window['go']['main']['App']['GetClusterInfo']();
}

export function GetConsumerGroupsOverview() {
  return window['go']['main']['App']['GetConsumerGroupsOverview']();
}

export function GetEndpointCompatibility() {
  return window['go']['main']['App']['GetEndpointCompatibility']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
