// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kconsole} from '../models';
import {rest} from '../models';

export function GetBrokerConfig(arg1:number):Promise<Array<kconsole.BrokerConfigEntry>|rest.Error>;

export function GetBrokersWithLogDirs():Promise<Array<kconsole.BrokerWithLogDirs>>;

export function GetClusterInfo():Promise<kconsole.ClusterInfo>;

export function GetConsumerGroupsOverview():Promise<Array<kconsole.ConsumerGroupOverview>|rest.Error>;

export function GetEndpointCompatibility():Promise<kconsole.EndpointCompatibility>;

export function Greet(arg1:string):Promise<string>;
