// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPartitionsToTopics(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPartitionsToTopics'](arg1, arg2, arg3);
}

export function AlterConfigs(arg1) {
  return window['go']['main']['App']['AlterConfigs'](arg1);
}

export function AlterPartitionAssignments(arg1) {
  return window['go']['main']['App']['AlterPartitionAssignments'](arg1);
}

export function CreateACL(arg1) {
  return window['go']['main']['App']['CreateACL'](arg1);
}

export function CreateACLs(arg1) {
  return window['go']['main']['App']['CreateACLs'](arg1);
}

export function CreateSchemaRegistrySchema(arg1, arg2) {
  return window['go']['main']['App']['CreateSchemaRegistrySchema'](arg1, arg2);
}

export function CreateTopic(arg1) {
  return window['go']['main']['App']['CreateTopic'](arg1);
}

export function CreateTopics(arg1) {
  return window['go']['main']['App']['CreateTopics'](arg1);
}

export function DeleteACLs(arg1) {
  return window['go']['main']['App']['DeleteACLs'](arg1);
}

export function DeleteACLsKafka(arg1) {
  return window['go']['main']['App']['DeleteACLsKafka'](arg1);
}

export function DeleteConsumerGroup(arg1) {
  return window['go']['main']['App']['DeleteConsumerGroup'](arg1);
}

export function DeleteConsumerGroupOffsets(arg1, arg2) {
  return window['go']['main']['App']['DeleteConsumerGroupOffsets'](arg1, arg2);
}

export function DeleteSchemaRegistrySubject(arg1, arg2) {
  return window['go']['main']['App']['DeleteSchemaRegistrySubject'](arg1, arg2);
}

export function DeleteSchemaRegistrySubjectConfig(arg1) {
  return window['go']['main']['App']['DeleteSchemaRegistrySubjectConfig'](arg1);
}

export function DeleteSchemaRegistrySubjectVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSchemaRegistrySubjectVersion'](arg1, arg2, arg3);
}

export function DeleteTopic(arg1) {
  return window['go']['main']['App']['DeleteTopic'](arg1);
}

export function DeleteTopicRecords(arg1) {
  return window['go']['main']['App']['DeleteTopicRecords'](arg1);
}

export function DeleteTopics(arg1) {
  return window['go']['main']['App']['DeleteTopics'](arg1);
}

export function DescribeConfigs(arg1) {
  return window['go']['main']['App']['DescribeConfigs'](arg1);
}

export function DescribeQuotas() {
  return window['go']['main']['App']['DescribeQuotas']();
}

export function EditConsumerGroupOffsets(arg1, arg2) {
  return window['go']['main']['App']['EditConsumerGroupOffsets'](arg1, arg2);
}

export function EditTopicConfig(arg1, arg2) {
  return window['go']['main']['App']['EditTopicConfig'](arg1, arg2);
}

export function GetAPIVersions() {
  return window['go']['main']['App']['GetAPIVersions']();
}

export function GetAllBrokerConfigs() {
  return window['go']['main']['App']['GetAllBrokerConfigs']();
}

export function GetAllTopicNames() {
  return window['go']['main']['App']['GetAllTopicNames']();
}

export function GetBrokerConfig(arg1) {
  return window['go']['main']['App']['GetBrokerConfig'](arg1);
}

export function GetBrokersWithLogDirs() {
  return window['go']['main']['App']['GetBrokersWithLogDirs']();
}

export function GetClusterInfo() {
  return window['go']['main']['App']['GetClusterInfo']();
}

export function GetConsoleInfo() {
  return window['go']['main']['App']['GetConsoleInfo']();
}

export function GetConsumerGroupsOverview(arg1) {
  return window['go']['main']['App']['GetConsumerGroupsOverview'](arg1);
}

export function GetEndpointCompatibility() {
  return window['go']['main']['App']['GetEndpointCompatibility']();
}

export function GetKafkaAuthorizerInfo() {
  return window['go']['main']['App']['GetKafkaAuthorizerInfo']();
}

export function GetKafkaConnectInfo() {
  return window['go']['main']['App']['GetKafkaConnectInfo']();
}

export function GetKafkaInfo() {
  return window['go']['main']['App']['GetKafkaInfo']();
}

export function GetKafkaVersion() {
  return window['go']['main']['App']['GetKafkaVersion']();
}

export function GetMetadata(arg1) {
  return window['go']['main']['App']['GetMetadata'](arg1);
}

export function GetSchemaRegistryConfig(arg1) {
  return window['go']['main']['App']['GetSchemaRegistryConfig'](arg1);
}

export function GetSchemaRegistryInfo() {
  return window['go']['main']['App']['GetSchemaRegistryInfo']();
}

export function GetSchemaRegistryMode() {
  return window['go']['main']['App']['GetSchemaRegistryMode']();
}

export function GetSchemaRegistrySchemaReferencedBy(arg1, arg2) {
  return window['go']['main']['App']['GetSchemaRegistrySchemaReferencedBy'](arg1, arg2);
}

export function GetSchemaRegistrySchemaTypes() {
  return window['go']['main']['App']['GetSchemaRegistrySchemaTypes']();
}

export function GetSchemaRegistrySubjectDetails(arg1, arg2) {
  return window['go']['main']['App']['GetSchemaRegistrySubjectDetails'](arg1, arg2);
}

export function GetSchemaRegistrySubjects() {
  return window['go']['main']['App']['GetSchemaRegistrySubjects']();
}

export function GetSchemaUsagesByID(arg1) {
  return window['go']['main']['App']['GetSchemaUsagesByID'](arg1);
}

export function GetTopicConfigs(arg1, arg2) {
  return window['go']['main']['App']['GetTopicConfigs'](arg1, arg2);
}

export function GetTopicDetails(arg1) {
  return window['go']['main']['App']['GetTopicDetails'](arg1);
}

export function GetTopicDocumentation(arg1) {
  return window['go']['main']['App']['GetTopicDocumentation'](arg1);
}

export function GetTopicsConfigs(arg1, arg2) {
  return window['go']['main']['App']['GetTopicsConfigs'](arg1, arg2);
}

export function GetTopicsOverview() {
  return window['go']['main']['App']['GetTopicsOverview']();
}

export function IncrementalAlterConfigs(arg1) {
  return window['go']['main']['App']['IncrementalAlterConfigs'](arg1);
}

export function IncrementalAlterConfigsKafka(arg1) {
  return window['go']['main']['App']['IncrementalAlterConfigsKafka'](arg1);
}

export function ListAllACLs(arg1) {
  return window['go']['main']['App']['ListAllACLs'](arg1);
}

export function ListMessages(arg1) {
  return window['go']['main']['App']['ListMessages'](arg1);
}

export function ListOffsets(arg1, arg2) {
  return window['go']['main']['App']['ListOffsets'](arg1, arg2);
}

export function ListPartitionReassignments() {
  return window['go']['main']['App']['ListPartitionReassignments']();
}

export function ListTopicConsumers(arg1) {
  return window['go']['main']['App']['ListTopicConsumers'](arg1);
}

export function ProducePlainRecords(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProducePlainRecords'](arg1, arg2, arg3);
}

export function ProduceRecord(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ProduceRecord'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function PutSchemaRegistryConfig(arg1, arg2) {
  return window['go']['main']['App']['PutSchemaRegistryConfig'](arg1, arg2);
}

export function SetPartitionsToTopics(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPartitionsToTopics'](arg1, arg2, arg3);
}

export function ValidateSchemaRegistrySchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateSchemaRegistrySchema'](arg1, arg2, arg3);
}
