---
name: Repository dispatch on push or release
on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"
    tags:
      - '*'
    branches:
      - '**'
permissions:
  id-token: write
  contents: read
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.RP_AWS_CRED_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.RP_AWS_CRED_ACCOUNT_ID }}:role/${{ vars.RP_AWS_CRED_BASE_ROLE_NAME }}${{ github.event.repository.name }}
      - uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/actions_bot_token
          parse-json-secrets: true
      - name: Repository Dispatch on Release
        uses: peter-evans/repository-dispatch@caebe2a7c967e9f927ff8780fea8e16e50b5ce40
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          repository: redpanda-data/kconsole-enterprise
          event-type: release
          client-payload: '{"branch": "master", "commit_sha": "${{ github.sha }}", "tag_name": "${{ github.event.release.tag_name }}"}'
      - name: Repository Dispatch on push
        uses: peter-evans/repository-dispatch@caebe2a7c967e9f927ff8780fea8e16e50b5ce40
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          repository: redpanda-data/kconsole-enterprise
          event-type: push
          client-payload: '{"branch": "${{ github.ref_name }}", "commit_sha": "${{ github.sha }}"}'
